Changing process.env globally so no need for envvars anymore
atlassian/github-for-jira pull request #1557
Opened 2022-08-30 06:44 UTC by mboudreau

**What's in this PR?**
Removing the need for `envVars` import, just use the node environment variable directly through `process.env`

**Why**
Because envVars was having a typing issue with e2e tests and needed a way to add more types to environment variables.  Plus, by doing this, we can make it so that each environment (test, dev, e2e, etc) can have a different typed set of environment variables and it also means that environment variables are dynamic now (not constant in const import)

**Added feature flags**
None

**Affected issues**  
None

**How has this been tested?**  
it compiles and all tests still work

**Whats Next?**
Continue working on e2e tests

2022-08-31 01:31 UTC, joshkay10 submitted a review, later dismissed

2022-08-31 02:10 UTC, gxueatlassian commented
Hi @mboudreau, I want to cautious here, so we are trading `runtime strong type checking` for `testing time flexibility`? The trade feels down grade from runtime perspective. 

And `envVar` I assume checking the mandatory part during startup, while `process.env` does not, that's also another thing I am cautious.

Can you elaborate what exactly do you mean by `Because envVars was having a typing issue with e2e tests`?

2022-08-31 02:12 UTC, gxueatlassian commented on src/config/env.ts
> +			NODE_ENV: EnvironmentEnum,
Not sure why this, but personally I prefer keep the `git diff` to minimum as much as possible.

2022-08-31 02:17 UTC, gxueatlassian commented
Hi @mboudreau , can you please elaborate what exactly do you mean by `Because envVars was having a typing issue with e2e tests ` (like with a code sample?) so that we could understand more of the why?

Some thing could be a caveat is, like depends on when we call `process.env`, the `env.ts` (envVars) may or may not be included at that time, so the value of `process.env.xxx` may or may not be checked/initialized. This is a bit tricky to wrap head around.

2022-08-31 02:54 UTC, bgvozdev commented
Blocking till the concerns are addressed/eliminated :feelsbadman:

2022-08-31 02:55 UTC, bgvozdev requested changes
Blocking till the concerns are addressed/eliminated :feelsbadman:

2022-08-31 03:55 UTC, mboudreau commented on src/config/env.ts
> -	SENTRY_DSN: process.env.SENTRY_DSN,
It can be (it's optional), it just doesn't matter at this point.  If it is, it would already be on `process.env`, hence we don't need to reset them.

2022-08-31 04:03 UTC, mboudreau commented on src/config/env.ts
> +};
I'm not sure I follow.  Are you saying you want all values of `process.env` to be just strings with no parsing?  I mean, we can do that, but we had already hit some issues where we had to use `process.env` in some places for testing and `envVars` in others.  Plus, it also doesn't fix the original issue that in some node environments (like test and e2e), we can extend the typings to include more variables that you definitely don't want available in the production code.

I mean, in this case, we're using `process.env` as _the_ single responsibility for all environment variables.  Adding it to another variable won't really change anything.  Also, when node starts, it captures system env vars and makes a hard copy from then on, meaning that any changes to system env vars needs to restart to process the new ones either way.

2022-08-31 05:02 UTC, mboudreau commented
@gxueatlassian in the .env files, we can have different variables for tests, e2e, dev or any other environment.  Currently with `envVars`, there's no way of globally changing the current typing of `EnvVars`, you can only extend, which means that the code then has to read it from a different place to get the correct typings for that specific environment.  It becomes super confusing instead of just everything using `process.env`

2022-08-31 07:00 UTC, gxueatlassian commented
Hi @mboudreau 

>there's no way of globally changing the current typing of EnvVars

Is it due to need a new field or need to change the value type of an existing field?

If former, can we do 
```javascript
export const envVars: EnvVars = {
	...process.env,
	...,
	getTestingVars: () => {
		return {
			VAR1: 'aaa',
			VAR2: 'bbb'
		}
	}
} as EnvVars;

export interface EnvVars {
	getTestingVars: ()=> {
			VAR1: 'aaa',
			VAR2: 'bbb'
	},
	NODE_ENV: EnvironmentEnum,
	MICROS_ENV: EnvironmentEnum;
	...
	// Cryptor
	CRYPTOR_URL: string;
	CRYPTOR_SIDECAR_CLIENT_IDENTIFICATION_CHALLENGE: string;
}

```

And so in the `xxx.test.ts` file, we can call `envVars.getTestingVars().VAR1`? With this, the production business code should never call `envVars.getTestingVars()`, still keep some sane in it. 

----

If it is due to need for change value type of existing, can you please give some example? I don't understand it.

2022-08-31 23:09 UTC, bgvozdev commented on src/config/env.ts
> +};
That's why I'm proposing to have some global functions, or, maybe, a class (`GitHubAppConfig`) where we'd have all the getters and we can do whatever logic in it we want.

`process.env` has a well-defined responsibility: propagate the process environment variables into the app. It is simple, well-defined, well-known and self-contained. I don't think we should change it.

If we want to have fancy typing around it, I think a new abstraction is needed

2022-09-01 00:40 UTC, mboudreau commented on src/config/env.ts
> +};
> process.env has a well-defined responsibility: propagate the process environment variables into the app. It is simple, well-defined, well-known and self-contained.

We're doing the same thing there, but just adding typings on top of it? Furthermore, that still doesn't solve any of the issues that this PR is trying to fix though.  I could try a convoluted way to capture any changes to process.env and copy those to another var, then need to create a global interface that other node envs can add to the types.  It's a lot of extra complications and I'm not even positive that it's possible.  I figured that this was the simplest way to do it.

2022-09-01 00:51 UTC, bgvozdev commented on src/config/env.ts
> +};
Looking at the code, like
```
PROXY: getProxyFromEnvironment()
...
NODE_ENV: nodeEnv,  # (where const nodeEnv: EnvironmentEnum = EnvironmentEnum[getNodeEnv()];)
...
GITHUB_REPO_URL: "https://github.com/atlassian/github-for-jira" # populating value that wasn't provided in envs
```
I cannot agree that we "just adding typing"...

2022-09-05 00:10 UTC, mboudreau commented
@bgvozdev I've updated the code, please review again

2022-09-05 00:13 UTC, bgvozdev approved these changes

2022-09-05 00:14 UTC, bgvozdev commented
> @bgvozdev I've updated the code, please review again

Awesome, @mboudreau , thanks a lot! And thanks for the patience 🙏 😄

2022-09-05 00:19 UTC, merged