Bugfix stop infinite resync
atlassian/github-for-jira pull request #1713
Opened 2022-10-27 19:13 UTC by joshkay10

**What's in this PR?**
If we fail a repository resync completely (after 4 getrepopage failures) we must stop retrying the same repo.
This stops us trying to sync invalid repos forever.

2022-10-27 19:21 UTC, mboudreau submitted a review, later dismissed
I still don't think this is the issue.  The task repository shouldn't fail unless the app was uninstalled or something since it's just looping through the repository list given to it.  This logic hasn't changed since implemented 6 months ago.  I think it's a side effect of something else.

Nonetheless, if it means not blocking, I'm happy to approve, but I don't think it's the root cause.

2022-10-27 22:33 UTC, bgvozdev approved these changes

2022-10-27 22:56 UTC, gxueatlassian commented on src/sync/installation.ts
> +	if (task === "repository" && nextTask.task === "repository") {
On around line 212 it has `const { task, cursor, repository } = nextTask;`, so isn't the `task` always === `nextTask.task`?

2022-10-27 22:56 UTC, gxueatlassian requested changes
Just one quick comment to address.

2022-10-28 00:09 UTC, gxueatlassian commented
In side `getNextTask` it has this line `if (subscription.repositoryStatus !== "complete") {`, so the change in this PR ( of setting `syncStatus` to `FAILED` ) won't prevent the app from re-pickup the repository task again?

2022-10-28 00:24 UTC, joshkay10 commented on src/sync/installation.ts
> +		return;
@gxueatlassian - correct, the update to failed alone wont do anything, mostly tidy up.
The return on the next line is what skips the task being fired again.

2022-10-28 02:39 UTC, joshkay10 commented
> I still don't think this is the issue. The task repository shouldn't fail unless the app was uninstalled or something since it's just looping through the repository list given to it. This logic hasn't changed since implemented 6 months ago. I think it's a side effect of something else.
> 
> Nonetheless, if it means not blocking, I'm happy to approve, but I don't think it's the root cause.

Agree, its not root cause, but it clean out the backfill. I do wonder if the installations i kicked off are uninstalled? Do we remove the entry on uninstall?

2022-10-28 02:52 UTC, gxueatlassian approved these changes

2022-10-28 02:52 UTC, merged