ARC-1730 Fix the reposyncstate bulk update duplicate issue
atlassian/github-for-jira pull request #1935
Opened 2023-03-01 05:14 UTC by gxueatlassian

**What's in this PR?**
Convert the buggy bulkUpdateOrCreate to a more simple loop and discovering repos in backfill

**Why**
Partial backfill has some bug that duplicate the RepoSyncStates in some cases.

**Added feature flags**
N/A

**Affected issues**  
ARC-1730

**How has this been tested?**  
Unit test

**Whats Next?**
N/A

2023-03-01 05:15 UTC, bgvozdev approved these changes

2023-03-01 05:19 UTC, mboudreau commented on src/models/reposyncstate.ts
> +			return RepoSyncState.findOrCreate({
...why `findOrCreate`?  This is suppose to be an `upsert`...

2023-03-01 05:21 UTC, mboudreau commented on src/models/reposyncstate.ts
> +		subscriptionId: number,
This is not the signature convention that we're using in the models

2023-03-01 05:21 UTC, mboudreau commented on src/models/reposyncstate.ts
> +		repositories: {
We already have a type for this

2023-03-01 05:22 UTC, mboudreau commented on src/models/reposyncstate.ts
> +	static async bulkCreateOrUpdateByRepos(
Maybe renaming it as `bulkUpsert` would make more sense?

2023-03-01 05:22 UTC, mboudreau requested changes
This is not the same functionality that it was doing before.

2023-03-07 00:45 UTC, gxueatlassian commented
Will have a look later.

2023-03-07 00:45 UTC, closed without merging