ISOC-3776 Installation webhook handler
atlassian/github-for-jira pull request #2307
Opened 2023-08-02 23:53 UTC by Harminder84

**What's in this PR?**
Implemented `installation` webhook handler to check whether security permissions has been accepted or not. If yes, then
 - update`isSecurityPermissionsAccepted` column in `Subscriptions` table to true
 -  Submit request to Jira to link security workspace

**Why**
We are introducing new permissions to access `dependabot_alerts` and `secret_scanning`. Once these permissions are made available in the GH app, the GH Admin will need to accept them. We will use this data to track customers whose permission requests are still pending. Backfill for security VULNS will also be triggered on permission acceptance 

**Added feature flags**
ENABLE_GITHUB_SECURITY_IN_JIRA

**Affected issues**  
[ISOC-3776]

**How has this been tested?**  
Unit test
Local

2023-08-03 03:33 UTC, gxueatlassian commented on src/github/installation.ts
> +		if (subscription) {
no need for `if`?

2023-08-03 03:34 UTC, gxueatlassian commented on src/github/installation.ts
> +	const logger = context.log.child({
I don't think we need those
```
const logger = context.log.child({
		gitHubInstallationId,
		jiraHost
	});
```
Should be already set.

2023-08-03 03:38 UTC, gxueatlassian requested changes
Looks good ✅  to me, let me know once db scripts are ran for all env, then I can unblock this one.

2023-08-03 04:58 UTC, Harminder84 commented
@gxueatlassian, I ran the DB scripts for all three environments.

2023-08-06 23:33 UTC, gxueatlassian approved these changes

2023-08-06 23:34 UTC, merged