ISOC-3692 add code scanning alerts backfill
atlassian/github-for-jira pull request #2361
Opened 2023-08-22 04:41 UTC by auzwang

**What's in this PR?**
Adds Security in Jira `code_scanning_alert` backfill support. GitHub Security [Code Scanning Alerts](https://docs.github.com/en/rest/code-scanning/code-scanning?apiVersion=2022-11-28#list-code-scanning-alerts-for-a-repository) will be transformed and submitted as [Security Vulnerabilities in Jira](https://developer.atlassian.com/cloud/jira/software/rest/api-group-security-information/#api-rest-security-1-0-linkedworkspaces-bulk-post).

Code scanning alerts from PRs are not included in the REST API by default.

**Why**
Integrate GitHub with Security in Jira
https://hello.atlassian.net/wiki/spaces/CDX/pages/2673460294/RFC+GitHub+for+Jira+Security

**Added feature flags**
ENABLE_GITHUB_SECURITY_IN_JIRA

**Affected issues**
[ISOC-3692](https://softwareteams.atlassian.net/browse/ISOC-3692)

**How has this been tested?**  
Locally
Unit Tests

**Todo**
- scheduler test

2023-08-23 00:54 UTC, Harminder84 commented
Make a seperate PR for DB changes and run the DB script on all environments. Here is the run book to run DB schema migration - https://hello.atlassian.net/wiki/spaces/OTFS/pages/1958321242/HOWTO+Run+db+schema+migration+manually+on+ddev+stg+prod

2023-08-23 23:56 UTC, Harminder84 commented on src/sync/code-scanning-alerts.ts
> +const areAllBuildsEarlierThanFromDate = (alerts: CodeScanningAlertResponseItem[], fromDate: Date | undefined): boolean => {
This method name should be something like `areAllAlertsEarlierThanFromDate`

2023-08-24 00:16 UTC, gxueatlassian requested changes
LGTM, just blocking until DB migrated.

2023-08-25 01:58 UTC, auzwang commented
@gxueatlassian the DB migrations have been successfully run on all environments. Thanks @Harminder84 !

2023-08-25 03:11 UTC, gxueatlassian approved these changes

2023-08-28 05:27 UTC, merged