Edge case tests
atlassian/github-for-jira pull request #938
Opened 2021-11-28 23:46 UTC by tarakpurohit

2021-11-29 22:51 UTC, mboudreau commented on test/jira/multiple-jira.test.ts
> +		await Installation.destroy({ truncate: true });
You only need 1 of each.

2021-11-29 22:52 UTC, mboudreau commented on test/setup/setup.ts
> +	let jira2Host: string;
Please don't put this here as it's only specific to one test suite.  Please move it to the test suite file

2021-11-29 22:53 UTC, mboudreau commented on test/setup/setup.ts
> +	global.jira2Host = process.env.ALTERNATE_ATLASSIAN_URL || "https://test2-atlassian-instance.net";
Dont' use an env var for that, just set one in the test file.

2021-11-29 22:55 UTC, mboudreau requested changes
Great test to have.  A few comments to address.  Also, I'd probably place a lot of the nock JSON into it's own separate JSON file as it's kinda hard to read the tests with so many.

2021-11-30 06:05 UTC, mboudreau approved these changes
Much better :+1:

2021-12-01 05:38 UTC, bgvozdev approved these changes

2021-12-01 05:42 UTC, merged